### ISSUE TITLE
Use of picture without None check

### ISSUE THREAD

**Issue by AVeenstra** [divio/djangocms-picture#69]
The model `AbstractPicture` allows for the `picture` to be `None`. There is no check for this in `img_src` (djangocms_picture/models.py#L352).

Lines 356, 367, and 370 could break if the `picture` is `None`:
https://github.com/divio/djangocms-picture/blob/9d9fa80392f65daaa789b36f13bff920e26f4cca/djangocms_picture/models.py#L356
https://github.com/divio/djangocms-picture/blob/9d9fa80392f65daaa789b36f13bff920e26f4cca/djangocms_picture/models.py#L367
https://github.com/divio/djangocms-picture/blob/9d9fa80392f65daaa789b36f13bff920e26f4cca/djangocms_picture/models.py#L370

One possible error (which causes an internal server error):
`'NoneType' object has no attribute 'subject_location'`

Not sure if there exists some kind of placeholder for missing images, so will not create a pull request.

**Comment by FinalAngel** [comment]
@AVeenstra thanks for the report. A test case would also always be appreciated :) I'll try to have a look this week to confirm if it triggers an error if the image is missing.

**Comment by FinalAngel** [comment]
@AVeenstra I can confirm that the issue is valid. When deleting a referenced image in filer creates a `'NoneType' object has no attribute 'subject_location'` error

**Comment by AVeenstra** [comment]
Thanks a lot for the fix!

**Comment by FinalAngel** [comment]
You are very welcome @AVeenstra and thanks for the report. It will be released in the next version :)

**Comment by emibcn** [comment]
Last release 2.1.3 was on 12/12/2018. Maybe its time to release 2.1.4 (AKA: I'm hitting this bug on one of the projects I work on).

Thanks for the report and for the dev!

**Comment by sophiekovalevsky** [comment]
@AVeenstra thanks for reporting this. I just deleted one image that it was using with a plugin over a page and the system throws me the error. 
As we need to wait for the next release, what approach can be done to fix this bug in the mean time?

**Comment by AVeenstra** [comment]
You could update to the specific commit that fixes this issue, but be sure to subscribe to the repository so that you can update to an official release once it is available. Otherwise you will miss out on future updates and other bug fixes.

Install a specific commit with pip:
```bash
pip install git+ssh://git@github.com/divio/djangocms-picture.git@a9a8a64a8ce774a53870faa79e80d35067dcb13d
```
There is also another fix available (see #71), so you might want to use another commit hash.

**Comment by sophiekovalevsky** [comment]
> You could update to the specific commit that fixes this issue, but be sure to subscribe to the repository so that you can update to an official release once it is available. Otherwise you will miss out on future updates and other bug fixes.
> 
> Install a specific commit with pip:
> 
> ```shell
> pip install git+ssh://git@github.com/divio/djangocms-picture.git@a9a8a64a8ce774a53870faa79e80d35067dcb13d
> ```
> 
> There is also another fix available (see #71), so you might want to use another commit hash.

@AVeenstra I appreciate your time to reply. Done. Thanks.

**Comment by febsn** [comment]
I can still reproduce this error using the master branch as of today (Apr 12) when using the responsive image option. Specifically, the plugin fails trying to build the srcset in models.py in line 335:

    [...]/lib/python3.6/site-packages/djangocms_picture/models.py in img_srcset_data

        @property
        def img_srcset_data(self):
            if not self.is_responsive_image:
                return None
            srcset = []
            thumbnailer = get_thumbnailer(self.picture)

    [...]/lib/python3.6/site-packages/easy_thumbnails/files.py in get_thumbnailer
        if isinstance(obj, six.string_types):
            relative_name = obj
            obj = None
        if not relative_name:
            raise ValueError(
                "If object is not a FieldFile or Thumbnailer instance, the "
                "relative name must be provided")
        if isinstance(obj, File):
            obj = obj.file
        if isinstance(obj, Storage) or obj == default_storage:
            source_storage = obj

Could you please take this into account?

Also, is there a reason why value None is allowed for AbstractPicture's picture field? From my point of view it would make more sense to make this field required. A picture plugin without a picture doesn't seem to make much sense anyway…

**Comment by FinalAngel** [comment]
@febsn you can also add an external image instead, thats why it is not marked as mandatory.

I'd be happy for a PR including tests, the previous PR breaks the plugin in other scenarios.

**Comment by IslaBecker91031015** [comment]
I got this error when adding a new page of page type where image was missing. I fixed by adding this to picture.html:
Line 15:  {% if instance.img_src != none %}  and Line 36: {% endif %}
